services:
  app:
    environment:
      DB_CONNECTION: ${DB_CONNECTION}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      MYSQL_ATTR_SSL_CA: ${MYSQL_ATTR_SSL_CA:-}
      ALLOW_DESTRUCTIVE_DB_COMMANDS: ${ALLOW_DESTRUCTIVE_DB_COMMANDS:-false}
